Repository Granulate/gprofiler, pull requests merged in 2021-11, with the labels that each got.

#198 python: Allow passing "--python-mode py-spy" as well as "pyspy"
  README.md
  gprofiler/profilers/python.py
Labels: enhancement

#199 Update rbspy to 0.8.1
  scripts/rbspy_build.sh
Labels: Runtime/Ruby

#202 java: Build musl-based async-profiler and use where appropriate
  Dockerfile
  gprofiler/profilers/java.py
  pyi.Dockerfile
  scripts/async_profiler_build_glibc.sh
  scripts/async_profiler_build_musl.sh
  scripts/async_profiler_build_shared.sh
  scripts/async_profiler_env_glibc.sh
  scripts/async_profiler_env_musl.sh
  scripts/build_aarch64_container.sh
  scripts/build_aarch64_executable.sh
  scripts/list_needed_libs.sh
  tests/conftest.py
  tests/containers/java/musl.Dockerfile
  tests/test_java.py
Labels: enhancement

#201 Bugfix/python kernel headers
  gprofiler/profilers/python.py
Labels: bug

#204 java: Allow passing safemode to async-profiler
  gprofiler/profilers/java.py
  gprofiler/profilers/registry.py
  tests/test_java.py
  tests/test_sanity.py
Labels: enhancement, Runtime/Java

#205 lint: Enable black's string normalization
  deploy/dataflow/setup.py
  gprofiler/client.py
  gprofiler/docker_client.py
  gprofiler/log.py
  gprofiler/main.py
  gprofiler/metadata/cloud_metadata.py
  gprofiler/metadata/system_metadata.py
  gprofiler/profilers/__init__.py
  gprofiler/profilers/factory.py
  gprofiler/profilers/perf.py
  gprofiler/profilers/php.py
  gprofiler/profilers/python.py
  gprofiler/profilers/ruby.py
  gprofiler/utils.py
  lint.sh
Labels: enhancement

#209 Add --controller-pid
  gprofiler/main.py
Labels: enhancement

#203 utils: Add get_mnt_ns_ancestor()
  gprofiler/utils.py
Labels: enhancement

#211 Always wait for at least "duration" between profiling sessions
  gprofiler/main.py
Labels: bug

#206 java: Clean files via topmost ancestor's root instead of process root
  gprofiler/profilers/java.py
Labels: enhancement, Runtime/Java

#214 Emit a log message upon successfully uploading my logs
  gprofiler/main.py
Labels: enhancement

#213 Added java version parsing and enhanced version checks
  gprofiler/profilers/java.py
  requirements.txt
  tests/containers/java/Dockerfile
  tests/test_java.py
  tests/test_sanity.py
Labels: enhancement, Runtime/Java

#212 Java: Check for Hotspot error files after process termination
  gprofiler/main.py
  gprofiler/profilers/java.py
  gprofiler/profilers/python.py
  gprofiler/utils.py
  tests/conftest.py
  tests/containers/java/Dockerfile
  tests/containers/java/musl.Dockerfile
  tests/test_java.py
  tests/test_sanity.py
Labels: Runtime/Java

#218 java: not profiling processes that were injected with another async-profiler
  gprofiler/profilers/java.py
  tests/test_java.py
Labels: enhancement, Runtime/Java

#220 java: Disabling java profiling on hotspot error file detection
  gprofiler/profilers/java.py
  tests/test_java.py
Labels: enhancement, Runtime/Java

#210 python: PyPerf w/o kernel headers :)
  Dockerfile
  README.md
  deploy/docker-compose/docker-compose.yml
  deploy/ecs/gprofiler_task_definition.json
  deploy/k8s/gprofiler.yaml
  gprofiler/metadata/system_metadata.py
  gprofiler/profilers/python.py
  pyi.Dockerfile
  scripts/bcc_helpers_build.sh
  scripts/perf_build.sh
  scripts/pyperf_build.sh
  tests/conftest.py
  tests/test_executable.py
  tests/test_java.py
  tests/test_sanity.py
  tests/utils.py
Labels: enhancement, Runtime/Python

#222 java: async-profiler: Remove framebuf parameter
  gprofiler/profilers/java.py
Labels: Runtime/Java

#223 tests: Skip PyPerf test on centos:6
  tests/test_executable.py
Labels: bug

#225 java: Cleanup & fixes for the next release
  Dockerfile
  gprofiler/kernel_messages.py
  gprofiler/profilers/java.py
  tests/test_java.py
Labels: enhancement, Runtime/Java

#232 ci: Organize & separate to more files
  .github/workflows/build-container-and-deploy.yml
  .github/workflows/build-container-and-test.yml
  .github/workflows/build-executable-test-deploy.yml
Labels: enhancement

#230 java: Add JDK 14 on alpine to minimal versions
  gprofiler/profilers/java.py
Labels: enhancement, Runtime/Java

#231 java: Upgrade AP for a static libgcc build
  scripts/async_profiler_build_shared.sh
Labels: enhancement, Runtime/Java

#233 java: Filter signal codes only in proc_events callback (from all non-zero exit codes)
  gprofiler/profilers/java.py
Labels: enhancement, Runtime/Java
