Repository Granulate/gprofiler, pull requests merged in 2021-04, with the labels that each got.

#14 Revert "Update perf to a newer release (#3)"
  build.sh
Labels: bug

#16 java: Improve profiler robustness
  build.sh
  gprofiler/java.py
  gprofiler/main.py
  gprofiler/utils.py
  tests/conftest.py
Labels: enhancement

#17 perf: Use /tmp/gprofiler/perf-buildids as the buildid cache for perf
  gprofiler/perf.py
Labels: enhancement

#19 tests: More fine-grained testing for specific runtimes or profilers.
  tests/__init__.py
  tests/conftest.py
  tests/test_python.py
  tests/test_sanity.py
Labels: enhancement

#24 java: Explicitly chmod() libasyncProfiler.so in its target directory
  gprofiler/java.py
Labels: bug

#20 Check for availability of "nsenter" before attempting to use it
  README.md
  gprofiler/exceptions.py
  gprofiler/java.py
  gprofiler/utils.py
Labels: enhancement

#23 utils: Include command in run_process() logs
  gprofiler/utils.py
Labels: enhancement

#22 Log and continue on runtime profiler errors
  gprofiler/main.py
  gprofiler/utils.py
Labels: enhancement

#26 Bundle gProfiler to one executable
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .gitignore
  README.md
  cmp_tags.sh
  dev-requirements.txt
  enable_hook.sh
  gprofiler/java.py
  gprofiler/utils.py
  pyi.Dockerfile
  pyi_build.py
  pyinstaller.spec
  tests/conftest.py
  tests/test_executable.py
  tests/test_python.py
  tests/test_sanity.py
  tests/util.py
Labels: enhancement

#25 Log system info upon startup
  gprofiler/main.py
  gprofiler/utils.py
  requirements.txt
  tests/test_sanity.py
Labels: enhancement

#29 utils: Fix get_libc_version() on RHEL
  gprofiler/utils.py
  tests/test_executable.py
Labels: bug

#18 perf: Replace [unknown] symbols with the DSO path
  gprofiler/merge.py
Labels: enhancement

#33 deploy: Add k8s YAML
  README.md
  deploy/k8s/gprofiler.yaml
Labels: enhancement

#37 Improve README
  Dockerfile
  README.md
  deploy/k8s/gprofiler.yaml
  gprofiler/main.py
  images/studio.png
  lint.sh
Labels: documentation

#40 Change --profiling-interval units to seconds
  README.md
  gprofiler/main.py
Labels: enhancement

#41 java: Be graceful if process dies during profiling
  gprofiler/java.py
Labels: bug

#43 Log the Python version gProfiler runs with
  gprofiler/utils.py
Labels: enhancement

#46 Log the run mode (container / k8s container / ...)
  gprofiler/utils.py
Labels: enhancement

#49 Feature/support executables with statically linked python
  gprofiler/python.py
Labels: enhancement

#45 PyInstaller: Improvements & robustness
  gprofiler/python.py
  pyi.Dockerfile
  scripts/list_needed_libs.sh
Labels: enhancement

#42 python: PyPerf: Faster initialization + timeouts in snapshot()
  gprofiler/exceptions.py
  gprofiler/main.py
  gprofiler/python.py
  gprofiler/utils.py
  tests/test_libpython.py
Labels: enhancement

#51 Allow skipping flamegraph generation with --no-flamegraph
  gprofiler/main.py
Labels: enhancement
