Repository Granulate/gprofiler, pull requests merged in 2021-06, with the labels that each got.

#92 java: Execute "java" in the JDK version check via /proc/pid/exe
  gprofiler/java.py
  gprofiler/utils.py
Labels: bug

#93 Improve PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#97 deploy: k8s: Fix indentation errors in YAML
  deploy/k8s/gprofiler.yaml
Labels: bug

#91 java: Add async-profiler build logic, and upgrade it.
  .github/workflows/build.yml
  .github/workflows/ci.yml
  Dockerfile
  lint.sh
  pyi.Dockerfile
  scripts/async_profiler_build.sh
  scripts/async_profiler_env.sh
  scripts/build.sh
  tests/conftest.py
  tests/test_libpython.py
  tests/test_sanity.py
  tests/utils.py
Labels: enhancement

#101 Log command line of execution
  gprofiler/main.py
Labels: enhancement

#98 Get hostname from host UTS NS and log it
  README.md
  gprofiler/main.py
  gprofiler/merge.py
  gprofiler/utils.py
Labels: bug

#99 Include parameters in POST query string for requests logging
  gprofiler/client.py
  gprofiler/main.py
  gprofiler/merge.py
  gprofiler/utils.py
Labels: enhancement

#104 Raise error instead of infinitely looping when app container exits prematurely
  tests/conftest.py
Labels: bug

#107 Pin test requirements
  dev-requirements.txt
Labels: enhancement

#106 Add Ruby language support using rbspy
  Dockerfile
  README.md
  gprofiler/main.py
  gprofiler/php.py
  gprofiler/python.py
  gprofiler/ruby.py
  gprofiler/utils.py
  pyi.Dockerfile
  scripts/prepare_x86_64-unknown-linux-musl.sh
  scripts/rbspy_build.sh
  tests/conftest.py
  tests/containers/ruby/Dockerfile
  tests/containers/ruby/fibonacci.rb
  tests/test.sh
  tests/test_executable.py
  tests/test_sanity.py
Labels: enhancement

#108 Extract ProfilerInterface from ProfilerBase, and put more logic in the latter
  gprofiler/java.py
  gprofiler/merge.py
  gprofiler/perf.py
  gprofiler/php.py
  gprofiler/profiler_base.py
  gprofiler/python.py
  gprofiler/ruby.py
  gprofiler/types.py
  gprofiler/utils.py
Labels: enhancement

#111 Shrink Docker image size: 789 MB -> 328 MB
  Dockerfile
Labels: enhancement

#110 Handle grep's "not found" error in pgrep_maps()
  gprofiler/utils.py
  tests/test_executable.py
  tests/test_java.py
  tests/test_sanity.py
  tests/utils.py
Labels: bug

#114 Add version to query params
  gprofiler/client.py
Labels: enhancement

#89 Allow running without the system perf
  Dockerfile
  README.md
  gprofiler/java.py
  gprofiler/main.py
  gprofiler/merge.py
  gprofiler/perf.py
  gprofiler/php.py
  gprofiler/python.py
  gprofiler/ruby.py
  tests/conftest.py
  tests/test_libpython.py
  tests/test_sanity.py
  tests/utils.py
Labels: enhancement

#115 Allow disabling the init PID NS check
  gprofiler/main.py
Labels: enhancement

#109 python: Add --python-mode option
  README.md
  gprofiler/main.py
  gprofiler/python.py
  tests/test_libpython.py
Labels: enhancement

#118 Bump PyPerf version
  scripts/pyperf_build.sh
Labels: enhancement

#121 Fix incorrect scaling in merge_profiles()
  gprofiler/merge.py
Labels: bug

#123 utils: Don't leak NS fds in run_in_ns()
  gprofiler/utils.py
Labels: bug

#120 Add assert failure messages where missing
  gprofiler/python.py
  gprofiler/utils.py
Labels: enhancement

#124 Upgrade py-spy
  gprofiler/__init__.py
  scripts/pyspy_build.sh
Labels: enhancement

#119 Server Logging
  README.md
  gprofiler/__init__.py
  gprofiler/client.py
  gprofiler/docker_client.py
  gprofiler/exceptions.py
  gprofiler/java.py
  gprofiler/log.py
  gprofiler/main.py
  gprofiler/merge.py
  gprofiler/perf.py
  gprofiler/php.py
  gprofiler/profiler_base.py
  gprofiler/python.py
  gprofiler/ruby.py
  gprofiler/state.py
  gprofiler/utils.py
Labels: enhancement

#129 ruby: Run rbspy in silent mode
  gprofiler/ruby.py
Labels: enhancement

#128 python, ruby: Remove collapsed files after reading
  gprofiler/merge.py
  gprofiler/python.py
  gprofiler/ruby.py
Labels: bug

#130 utils: pgrep_maps(): Ignore "No such process" errors
  gprofiler/utils.py
Labels: enhancement

#133 ci: Reject non-matching version between git tag and code
  .github/workflows/build.yml
Labels: enhancement
