Repository Granulate/gprofiler, pull requests merged in 2021-12, with the labels that each got.

#234 tests: Test gProfiler with low privileges
  tests/conftest.py
  tests/containers/python/Dockerfile
  tests/test_executable.py
Labels: enhancement

#235 java: Paranoid profiling stop on suspicious events in kernel messages
  gprofiler/profilers/java.py
Labels: enhancement, Runtime/Java

#239 python: pyperf: Remove output files before starting
  gprofiler/profilers/python.py
Labels: bug

#237 ci: deploy-executable needs build-executable, not test-executable
  .github/workflows/build-executable-test-deploy.yml
Labels: bug

#241 gProfiler 1.2.10 & upgrade Java's async-profiler
  gprofiler/__init__.py
  scripts/async_profiler_build_shared.sh
Labels: bug, Runtime/Java

#246 Prevent registering of profiler arguments with a wrong dest name
  gprofiler/profilers/registry.py
Labels: enhancement

#253 python: pyperf: Bump bpf_get_stack_offset version to v0.0.3
  scripts/bcc_helpers_build.sh
Labels: bug, Runtime/Python
