Repository Granulate/gprofiler, pull requests merged in 2022-04, with the labels that each got.

#329 Exit with an error log if all profilers are disabled
  gprofiler/exceptions.py
  gprofiler/main.py
  gprofiler/profilers/factory.py
Labels: enhancement

#333 Don't upload logs if profile API version is v1
  gprofiler/main.py
Labels: enhancement

#325 docs: Pass --token, --service-name with =
  README.md
Labels: enhancement

#337 java: Handle /tmp being noexec (on host / container)
  gprofiler/exceptions.py
  gprofiler/profilers/java.py
  gprofiler/utils/__init__.py
  gprofiler/utils/fs.py
  tests/conftest.py
  tests/test_java.py
Labels: enhancement, Runtime/Java

#339 java: Upgrade async-profiler (regression in build scripts, not using -static-* flags)
  scripts/async_profiler_build_shared.sh
  tests/containers/java/musl.Dockerfile
  tests/test_java.py
Labels: bug

#336 Improve warning log messages about failing optional features
  gprofiler/kernel_messages.py
  gprofiler/profilers/java.py
Labels: enhancement

#326 ProfileData API
  gprofiler/gprofiler_types.py
  gprofiler/main.py
  gprofiler/merge.py
  gprofiler/metadata/application_identifiers.py
  gprofiler/metadata/application_metadata.py
  gprofiler/metadata/enrichment.py
  gprofiler/profilers/java.py
  gprofiler/profilers/perf.py
  gprofiler/profilers/php.py
  gprofiler/profilers/profiler_base.py
  gprofiler/profilers/python.py
  gprofiler/profilers/ruby.py
  tests/conftest.py
  tests/test_appids.py
  tests/test_java.py
  tests/test_libpython.py
  tests/test_sanity.py
  tests/utils.py
Labels: enhancement

#345 Log arguments
  gprofiler/main.py
Labels: enhancement

#347 utils: fs: Use randomized path for test script
  gprofiler/utils/fs.py
Labels: bug

#348 java: Increase jattach timeout & make it configurable
  gprofiler/profilers/java.py
  tests/utils.py
Labels: enhancement
