Repository Granulate/gprofiler, pull requests merged in 2022-09, with the labels that each got.

#456 python: pyperf: Ensure we run in init PID NS
  gprofiler/profilers/python.py
Labels: enhancement

#463 dotnet: Add _[net] frame suffix to all frames from dotnet-trace
  gprofiler/profilers/dotnet.py
  gprofiler/utils/speedscope.py
Labels: enhancement

#460 Colaesce process basename checks & check argv[0] as well
  gprofiler/profilers/dotnet.py
  gprofiler/profilers/java.py
  gprofiler/profilers/perf.py
  gprofiler/profilers/python.py
  gprofiler/profilers/ruby.py
  gprofiler/utils/process.py
  tests/containers/java/Dockerfile
  tests/test_java.py
  tests/test_libpython.py
  tests/utils.py
Labels: enhancement

#469 perf: Default to 'smart' mode
  README.md
  gprofiler/profilers/perf.py
Labels: enhancement

#471 appids: uwsgi: Handle additional '.ini' options, and avoid "uwsgi: None" appid
  gprofiler/metadata/application_identifiers.py
  tests/test_appids.py
Labels: enhancement

#472 python: Get Python version in app metadata for uwsgi apps
  gprofiler/metadata/application_metadata.py
  gprofiler/profilers/python.py
Labels: enhancement

#477 tests: Break up application_docker_images()
  tests/conftest.py
  tests/containers/python/libpython.Dockerfile
  tests/test_java.py
  tests/test_python.py
  tests/type_utils.py
Labels: enhancement

#486 tests: Build images lazily
  tests/conftest.py
Labels: enhancement

#487 Add shellcheck in CI
  .github/workflows/linters.yml
  CONTRIBUTING.md
  scripts/async_profiler_build_glibc.sh
  scripts/async_profiler_build_shared.sh
  scripts/async_profiler_env_musl.sh
  scripts/bcc_helpers_build.sh
  scripts/build_aarch64_container.sh
  scripts/build_aarch64_executable.sh
  scripts/build_x86_64_container.sh
  scripts/build_x86_64_executable.sh
  scripts/cmp_tags.sh
  scripts/copy_resources_from_image.sh
  scripts/libunwind_build.sh
  scripts/list_needed_libs.sh
  scripts/perf_build.sh
  scripts/phpspy_build.sh
  scripts/prepare_machine-unknown-linux-musl.sh
  scripts/pyperf_build.sh
  scripts/pyspy_build.sh
  scripts/rbspy_build.sh
  scripts/verify_tag.sh
  shell_lint.sh
Labels: enhancement

#495 Import windows specific profilers only
  gprofiler/profilers/__init__.py
Labels: windows

#498 Log HTTP proxy upon connection error
  README.md
  gprofiler/main.py
  gprofiler/utils/proxy.py
Labels: enhancement

#508 tests: Turn command_line fixture lazy
  tests/conftest.py
  tests/test_java.py
  tests/test_sanity.py
  tests/utils.py
Labels: tests
