Repository Granulate/gprofiler, pull requests merged in 2022-11, with the labels that each got.

#566 Fix using attach_maps on NodeJS 14+
  gprofiler/profilers/node.py
  tests/test_node.py
Labels: runtime/nodejs

#578 Add logging for changing DSO state and creating debugger socket
  gprofiler/profilers/node.py
Labels: runtime/nodejs

#577 Use with statement when creating Node.js debugger socket
  gprofiler/profilers/node.py
Labels: runtime/nodejs

#546 "Upload profiling data" mode
  README.md
  gprofiler/main.py
  gprofiler/merge.py
  gprofiler/utils/__init__.py
Labels: enhancement

#585 nodejs: Fix removing file that doesn't exist
  gprofiler/profilers/node.py
  gprofiler/profilers/perf.py
Labels: runtime/nodejs

#589 Fix using wrong variable in snapshot() function
  gprofiler/profilers/perf.py
Labels: runtime/nodejs

#442 GProfiler with Py-Spy on Windows
  Dockerfile
  exe-requirements.txt
  gprofiler/main.py
  gprofiler/metadata/system_metadata.py
  gprofiler/profilers/factory.py
  gprofiler/profilers/python.py
  gprofiler/profilers/registry.py
  pyi.Dockerfile
  scripts/pyspy_build.sh
  scripts/pyspy_commit.txt
  scripts/pyspy_tag.txt
  scripts/windows/build-pyspy.bat
  scripts/windows/build.bat
Labels: windows

#591 nodejs: Implement getting appid
  gprofiler/metadata/application_identifiers.py
  gprofiler/profilers/perf.py
  tests/conftest.py
  tests/test_appids.py
Labels: runtime/nodejs

#598 nodejs: Fix problem with permissions
  gprofiler/profilers/node.py
Labels: runtime/nodejs

#599 Bugfix/multiple-containers-being-run-in-tests
  tests/test_preconditions.py
Labels: bug, tests

#601 ruby: Implement getting appid
  gprofiler/metadata/application_identifiers.py
  gprofiler/profilers/ruby.py
  tests/conftest.py
  tests/test_appids.py
Labels: runtime/ruby

#581 Feature/basic allocation profiling
  gprofiler/consts.py
  gprofiler/main.py
  gprofiler/merge.py
  gprofiler/metadata/metadata_collector.py
  gprofiler/profilers/dotnet.py
  gprofiler/profilers/factory.py
  gprofiler/profilers/java.py
  gprofiler/profilers/perf.py
  gprofiler/profilers/php.py
  gprofiler/profilers/profiler_base.py
  gprofiler/profilers/python.py
  gprofiler/profilers/python_ebpf.py
  gprofiler/profilers/registry.py
  gprofiler/profilers/ruby.py
  gprofiler/utils/__init__.py
  mypy.ini
  requirements.txt
  tests/test_node.py
  tests/test_perf.py
  tests/test_profiling_mode.py
  tests/test_python.py
  tests/test_sanity.py
  tests/utils.py
Labels: enhancement, runtime/java

#571 Introduce diagnostics mode
  gprofiler/diagnostics.py
  gprofiler/main.py
  gprofiler/metadata/enrichment.py
  gprofiler/profilers/java.py
  tests/conftest.py
Labels: enhancement

#606 bugfix/stdout-logs-utc
  gprofiler/log.py
Labels: bug

#607 java: Ensure fdtransfer lasts for as long as jattach timeout
  gprofiler/profilers/java.py
  scripts/async_profiler_build_shared.sh
Labels: bug, runtime/java

#610 nodejs: attach-maps: Build nodejs resources on centos7 image
  Dockerfile
  pyi.Dockerfile
  scripts/build_x86_64_executable.sh
  scripts/node_builder_glibc_env.sh
  tests/conftest.py
  tests/containers/nodejs/Dockerfile
  tests/test_node.py
  tests/utils.py
Labels: runtime/nodejs

#611 Block building glibc on aarch64, update nodejs glibc builder image in aarch64 scripts
  scripts/build_aarch64_container.sh
  scripts/build_aarch64_executable.sh
  scripts/build_node_package.sh
  scripts/node_builder_glibc_env.sh
Labels: runtime/nodejs, aarch64

#614 Fix aarch64 centos image issue
  Dockerfile
  pyi.Dockerfile
  scripts/build_x86_64_executable.sh
Labels: runtime/nodejs, build

#597 Use modern Python for gProfiler exe
  exe-requirements.txt
  pyi.Dockerfile
  scripts/openssl_build.sh
  scripts/python310_build.sh
Labels: enhancement, build

#596 java: Upgrade to async-profiler v2.9
  CONTRIBUTING.md
  Dockerfile
  pyi.Dockerfile
  scripts/async_profiler_build_glibc.sh
  scripts/async_profiler_build_musl.sh
  scripts/async_profiler_build_shared.sh
  scripts/async_profiler_env_glibc.sh
Labels: runtime/java

#619 perf: Set stdout and stderr streams of perf process to non blocking
  gprofiler/profilers/perf.py
Labels: bug
