Repository Granulate/gprofiler, pull requests merged in 2022-07, with the labels that each got.

#399 README: Always use TMPDIR=/proc/self/cwd
  README.md
Labels: enhancement

#391 Node perf metadata
  gprofiler/metadata/application_metadata.py
  gprofiler/profilers/perf.py
  gprofiler/profilers/ruby.py
  tests/conftest.py
  tests/containers/nodejs/Dockerfile
  tests/test_app_metadata.py
Labels: Runtime/Node

#376 java: parse_jvm_version(): Handle single-digit build number suffix
  gprofiler/profilers/java.py
Labels: bug

#406 fix: Update rbspy with fix for failing build
  scripts/rbspy_build.sh
Labels: bug

#403 java: Upgrade to AP v2.8.2
  scripts/async_profiler_build_shared.sh
Labels: enhancement

#409 java: Upgrade async-profiler v2.8.3g1
  scripts/async_profiler_build_shared.sh
Labels: enhancement

#408 Avoid double duration wait in SpawningProcessProfilerBase
  gprofiler/profilers/profiler_base.py
Labels: bug

#420 Add perf tests
  gprofiler/merge.py
  gprofiler/profilers/perf.py
  tests/conftest.py
  tests/containers/native/dwarf.Dockerfile
  tests/containers/native/fp.Dockerfile
  tests/containers/native/native.c
  tests/test_merge.py
  tests/test_perf.py
  tests/utils.py
Labels: enhancement
