Repository Granulate/gprofiler, pull requests merged in 2022-06, with the labels that each got.

#367 Allow logging HTTP requests with curlify (for debugging purposes)
  gprofiler/client.py
  gprofiler/main.py
  requirements.txt
Labels: enhancement

#369 Document HTTP proxies usage
  README.md
Labels: documentation

#370 java: Profile Zing with AP & refactor version checks
  gprofiler/profilers/java.py
Labels: enhancement

#371 java: Log "java -version" output
  gprofiler/profilers/java.py
Labels: enhancement

#372 perf: Upgrade elfutils & disable libdebuginfod
  scripts/perf_env.sh
Labels: bug

#373 Add hadolint (Dockerfiles linter) and begin work on shellcheck
  .github/workflows/linters.yml
  .hadolint.yaml
  Dockerfile
  dockerfile_lint.sh
  lint.sh
  pyi.Dockerfile
  scripts/bcc_helpers_build.sh
  scripts/build_aarch64_executable.sh
  scripts/build_x86_64_executable.sh
  scripts/phpspy_build.sh
  scripts/phpspy_env.sh
  scripts/pyperf_build.sh
  shell_lint.sh
Labels: enhancement

#363 Upgrade async-profiler to v2.8
  gprofiler/gprofiler_types.py
  gprofiler/profilers/java.py
  scripts/async_profiler_build_shared.sh
  scripts/async_profiler_env_glibc.sh
  scripts/async_profiler_env_musl.sh
  tests/test_java.py
  tests/utils.py
Labels: enhancement

#392 Fix skip folders in lint script
  .gitignore
  lint.sh
Labels: bug
