Repository Granulate/gprofiler, pull requests merged in 2022-02, with the labels that each got.

#286 Bugfix/ uwsgi-config-file-parsing
  gprofiler/metadata/application_identifiers.py
Labels: bug

#285 appids: Support gunicorns which use setproctitle()
  gprofiler/metadata/application_identifiers.py
Labels: Runtime/Python

#284 utils: Raise NoSuchProcess from process_comm() if process is missing
  gprofiler/profilers/java.py
  gprofiler/profilers/python.py
  gprofiler/profilers/ruby.py
  gprofiler/utils/__init__.py
  gprofiler/utils/process.py
Labels: enhancement

#282 mypy: Enable mypy strict mode
  dev-requirements.txt
  gprofiler/client.py
  gprofiler/docker_client.py
  gprofiler/exceptions.py
  gprofiler/gprofiler_types.py
  gprofiler/kernel_messages.py
  gprofiler/log.py
  gprofiler/main.py
  gprofiler/merge.py
  gprofiler/metadata/py_module_version.py
  gprofiler/metadata/system_metadata.py
  gprofiler/profilers/java.py
  gprofiler/profilers/perf.py
  gprofiler/profilers/php.py
  gprofiler/profilers/profiler_base.py
  gprofiler/profilers/python.py
  gprofiler/profilers/registry.py
  gprofiler/profilers/ruby.py
  gprofiler/system_metrics.py
  gprofiler/usage_loggers.py
  gprofiler/utils/__init__.py
  mypy.ini
  tests/conftest.py
  tests/containers/python/lister.py
  tests/test_java.py
  tests/test_libpython.py
  tests/test_sanity.py
  tests/type_utils.py
  tests/utils.py
Labels: enhancement

#289 appids: Show the original identifier (per the user) as well as the normalized one
  gprofiler/metadata/application_identifiers.py
  tests/conftest.py
  tests/test_appid.py
  tests/test_appids.py
Labels: enhancement

#279 Return profiling error stack in all error/skip cases of _profile_process
  gprofiler/profilers/java.py
  gprofiler/profilers/profiler_base.py
  gprofiler/profilers/python.py
Labels: enhancement

#291 Python: Bugfix: Don't emit incorrect Python versions
  gprofiler/metadata/py_module_version.py
Labels: bug, Runtime/Python

#268 Fix CI by reordering tests
  tests/conftest.py
  tests/test_sanity.py
Labels: bug

#305 java: repr(jvm_version) in all sites, as it's not serializable
  gprofiler/log.py
  gprofiler/profilers/java.py
Labels: bug

#304 Build async-profiler on CentOS 7
  Dockerfile
  pyi.Dockerfile
  scripts/async_profiler_build_shared.sh
  scripts/async_profiler_env_glibc.sh
Labels: Runtime/Java
