Repository Granulate/gprofiler, pull requests merged in 2022-03, with the labels that each got.

#310 Improve server connection error log message
  gprofiler/main.py
Labels: enhancement

#309 java: Fix _check_async_profiler_loaded() for cases where resolved storage path differs
  gprofiler/profilers/java.py
  gprofiler/utils/__init__.py
Labels: Runtime/Java

#308 java: Simplify complexity of atomic copies by ensuring sync
  gprofiler/profilers/java.py
  gprofiler/utils/fs.py
Labels: Runtime/Java

#312 Removes intermediate containers when using docker SDK to build images.
  tests/conftest.py
  tests/test_libpython.py
Labels: bug

#316 java: Upgrade to async-profiler v2.7 + J9 support
  gprofiler/profilers/java.py
  gprofiler/utils/process.py
  scripts/async_profiler_build_shared.sh
  tests/conftest.py
  tests/containers/java/Dockerfile
  tests/pytest.ini
  tests/test_java.py
  tests/test_sanity.py
Labels: enhancement

#330 Fix celery app name when no app name is given in args
  gprofiler/metadata/application_identifiers.py
  tests/test_appids.py
Labels: bug

#332 Support celery appids with queue workers
  .gitignore
  gprofiler/metadata/application_identifiers.py
  tests/test_appids.py
Labels: enhancement
