Repository Granulate/gprofiler, pull requests merged in 2023-05, with the labels that each got.

#784 Spark sa tests
  tests/conftest.py
  tests/containers/spark/Dockerfile
  tests/test_spark.py
  tests/utils.py
Labels: spark metrics

#786 java: Add JDK 19 to min supported versions
  gprofiler/profilers/java.py
Labels: enhancement

#622 Build latest version of bcc
  Dockerfile
  gprofiler/profilers/perf.py
  gprofiler/profilers/php.py
  gprofiler/profilers/python_ebpf.py
  gprofiler/utils/__init__.py
  pyi.Dockerfile
  scripts/bcc_helpers_build.sh
  scripts/pyperf_build.sh
  scripts/pyperf_env.sh
  scripts/staticx_for_pyperf_patch.diff
Labels: runtime/python

#793 docs: Add OpenShift SCCs explanation
  README.md
  deploy/k8s/openshift/scc.yaml
Labels: documentation

#778 Update remote logs service name after --databricks-job-name-as-service-name
  gprofiler/log.py
  gprofiler/main.py
Labels: bug
