Repository Granulate/gprofiler, pull requests merged in 2023-04, with the labels that each got.

#756 utils: process exceptions: Strict type checks
  gprofiler/exceptions.py
  gprofiler/profilers/java.py
  gprofiler/profilers/python.py
  gprofiler/profilers/python_ebpf.py
  gprofiler/utils/__init__.py
  gprofiler/utils/perf.py
Labels: bug

#761 Filter PIDs to profile
  gprofiler/gprofiler_types.py
  gprofiler/main.py
  gprofiler/profiler_state.py
  gprofiler/profilers/perf.py
  gprofiler/profilers/php.py
  gprofiler/profilers/profiler_base.py
  gprofiler/profilers/python_ebpf.py
  tests/conftest.py
  tests/test_sanity.py
Labels: enhancement

#627 exited container cleanup
  tests/conftest.py
  tests/test_executable.py
  tests/utils.py
Labels: tests

#777 python: Prevent implicit fallback to py-spy if pyperf is explicitly requested
  gprofiler/profilers/python.py
  tests/test_executable.py
Labels: bug, runtime/python

#781 tests: executable: Test on ubuntu:22.04 and debian:11
  .github/workflows/build-executable-test-deploy.yml
Labels: tests
