Repository Granulate/gprofiler, pull requests merged in 2023-01, with the labels that each got.

#650 Don't try getting container name for PIDs 0 / -1
  gprofiler/containers_client.py
  gprofiler/profilers/perf.py
  gprofiler/utils/perf.py
Labels: bug

#651 utils: run_process(): Don't try writing stdin more than once
  gprofiler/utils/__init__.py
Labels: bug

#652 python: Add missing NoSuchProcess catch
  gprofiler/profilers/python.py
Labels: bug

#655 java: async-profiler: Default async-profiler safemode of PROBE_SP
  gprofiler/profilers/java.py
Labels: runtime/java

#657 docs: Document network requirements
  README.md
Labels: enhancement

#656 Improve app metadata robustness
  gprofiler/metadata/application_metadata.py
  gprofiler/profilers/profiler_base.py
Labels: enhancement

#661 java-ap: remove semicolon patch
  scripts/async_profiler_build_shared.sh
  tests/test_java.py
Labels: runtime/java

#662 Print pyinstaller errors
  scripts/check_pyinstaller.sh
Labels: build
